# Docker Compose 파일 형식 버전
name: project-protostar-frontend
services:
  next-dev:
    container_name: protostar-next-dev
    build:
      context: .
      target: dev_runner
    command: sh -c "pnpm run dev"
    ports:
      - '5858:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  next-prod:
    container_name: protostar-next-prod
    build:
      context: .
    ports:
      - '5858:3000'
    environment:
      - NODE_ENV=production
