apiVersion: apps/v1
kind: Deployment
metadata:
  name: protostar-frontend
  namespace: service
  labels:
    app: protostar
    tier: frontend
    env: dev
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: protostar
      tier: frontend
  template:
    metadata:
      labels:
        app: protostar
        tier: frontend
        env: dev
    spec:
      # nodeSelector:
      # kubernetes.io/hostname: A5
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/paul2021-r/project-protostar-frontend:75
          ports: 
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
