apiVersion: v1
kind: Service
metadata:
  name: protostar-frontend-service
  namespace: service
  labels:
    app: protostar
    tier: frontend
spec:
  selector:
    app: protostar
    tier: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP